created: 2026-09-05T03:28:55.917Z
updated: 2026-09-05T03:29:27.148Z
update_count: 7
last_field: note
git_commit: cbac48b
git_branch: development
children:
  - agent
  - cli
  - core
  - models
  - services
  - storage
  - tui
