created: 2026-09-05T03:29:59.349Z
updated: 2026-09-05T03:29:59.350Z
update_count: 1
last_field: diagram
kind: nested-class
title: services
children:
  - classifier
  - context7
  - llm
  - rubygems
parentPath: []
